name: Build apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: app_version
        run: |
          APP_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.4
          channel: stable
      - run: flutter pub get
      - run: flutter build apk
      - run: |
          mkdir arts
          cp build/app/outputs/flutter-apk/*.apk arts/
      - uses: actions/upload-artifact@v4
        with:
          name: app-v${{ steps.app_version.outputs.app_version }}
          path: arts/
          retention-days: 1
          
